custom_auth/urls.py
from django.urls import path

from . import views

app_name = "custom_auth"
urlpatterns = [
    path("", views.index, name="index"),
    path("password", views.password_change, name="password_change"),
    path("email", views.change_email, name="email_change"),
    path("edit", views.edit_profile, name="edit_profile"),
    path("two_auth", views.list_two_auth, name="list_two_auth"),
    path("two_auth/add", views.add_two_auth, name="add_two_auth"),
]

notice/urls.py
from django.urls import path

from . import views

app_name = "notice"
urlpatterns = [
    path("", views.index, name="index"),
]

shifttimes/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from custom_auth.views import activate_user
from shifttimes import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("", views.index, name="index"),
    path("forget/", include("custom_auth.forget_urls")),
    path("notice/", include("notice.urls")),
    path("activate/<uuid:activate_token>/", activate_user, name="activate_user"),
    path("profile/", include("custom_auth.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

shifttimes/models.py
from django.db import models


class MediumTextField(models.TextField):
    def db_type(self, connection):
        if connection.settings_dict["ENGINE"] == "django.db.backends.mysql":
            return "mediumtext"
        else:
            return super(MediumTextField, self).db_type(connection=connection)

shifttimes/views.py
from django.contrib.auth import logout as user_logout, authenticate, login as user_login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from shifttimes.form import LoginForm


@login_required
def index(request):
    context = {}
    return render(request, "index.html", context)


def login(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user:
                user_login(request, user)
                return redirect("/")

    else:
        form = LoginForm()
    context = {'form': form}
    return render(request, "login.html", context)


@login_required
def logout(request):
    user_logout(request)
    context = {}
    return render(request, "logout.html", context)

shifttimes/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>シフト管理システム</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.2/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <style>
        body {
            padding-top: 5rem;
        }
    </style>
    {% block extrahead %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'index' %}">　シフト管理</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% include 'navbar.html' %}
        </ul>
    </div>
</nav>

<main role="main" class="container">
    {% block content %}
    {% endblock content %}
</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"
        integrity="sha512-rmZcZsyhe0/MAjquhTgiUcb4d9knaFc7b5xAfju483gbEXTkeJRUMIPk6s3ySZMYUHEcjKbjLjyddGWMrNEvZg=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/locale/ja.min.js"
        integrity="sha512-rElveAU5iG1CzHqi7KbG1T4DQIUCqhitISZ9nqJ2Z4TP0z4Aba64xYhwcBhHQMddRq27/OKbzEFZLOJarNStLg=="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.5/index.global.min.js'></script>

{% block javascript %}
{% endblock javascript %}
</html>

shifttimes/templates/done.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2>{{ text }}</h2>
          <a class="btn btn-primary btn-sm"
             href="{% url 'custom_auth:index' %}" role="button"
             aria-expanded="false">Profileに戻る</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

shifttimes/templates/error.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2>{{ error }}</h2>
          <h2>{{ text }}</h2>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

shifttimes/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="h3 mb-3 font-weight-normal">ログインが必要です</h1>
    {#    <form class="form-signin">#}
    {#        <h1 class="h3 mb-3 font-weight-normal">ログインが必要です</h1>#}
    {#        <label for="inputId" class="sr-only">ID</label>#}
    {#        <input type="text" id="inputId" class="form-control" placeholder="ID" required autofocus>#}
    {#        <label for="inputPassword" class="sr-only">Password</label>#}
    {#        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>#}
    {#        <br/>#}
    {#        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>#}
    {#    </form>#}
{% endblock content %}

{% block javascript %}
{% endblock javascript %}

shifttimes/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="h3 mb-3 font-weight-normal">ログインが必要です</h1>
    <div class="container">
        <div class="p-3 border bg-light">
            <form method="post" class="needs-validation" novalidate>
                <div class="row g-2">
                    <div class="col-3">
                        <label for="id_username">{{ form.username.label }}</label>
                        {{ form.username }}
                    </div>
                    <div class="col-3">
                        <label for="id_password">{{ form.password.label }}</label>
                        {{ form.password }}
                    </div>
                    <div class="col-4">
                    </div>
                </div>
                <br/>
                <button class="btn btn-primary" type="submit">ログイン</button>
                {% csrf_token %}
            </form>
        </div>
    </div>
    {#    <form class="form-signin">#}
    {#        <h1 class="h3 mb-3 font-weight-normal">ログインが必要です</h1>#}
    {#        <label for="inputId" class="sr-only">ID</label>#}
    {#        <input type="text" id="inputId" class="form-control" placeholder="ID" required autofocus>#}
    {#        <label for="inputPassword" class="sr-only">Password</label>#}
    {#        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>#}
    {#        <br/>#}
    {#        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>#}
    {#    </form>#}
{% endblock content %}

{% block javascript %}
{% endblock javascript %}

shifttimes/templates/logout.html
{% extends 'base.html' %}

{% block content %}
    <h1>ログアウトしました</h1>
{% endblock content %}

{% block javascript %}
{% endblock javascript %}

shifttimes/templates/navbar.html
<li class="nav-item">
</li>
<li class="nav-item">
</li>
{% if request.user.is_anonymous %}
  <a class="nav-link " href="{% url 'login' %}" role="button" aria-expanded="false">ログイン</a>
{% else %}
  <a class="nav-link " href="{% url 'notice:index' %}" role="button" aria-expanded="false">お知らせ</a>
  {#  <a class="nav-link " href="{% url 'resource:resource' %}" role="button" aria-expanded="false">シフト記入</a>#}
  {#  <a class="nav-link " href="{% url 'assignment:search' %}" role="button" aria-expanded="false">設定</a>#}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" role="button" data-bs-toggle="dropdown"
       aria-expanded="false">管理メニュー</a>
    <div class="dropdown-menu" aria-labelledby="dropdown01">
      {% if request.user.is_staff %}
        <a class="dropdown-item" href="{% url 'admin:index' %}">通知設定</a>
        <a class="dropdown-item" href="{% url 'admin:index' %}">管理者画面</a>
      {% endif %}
      {#      <a class="dropdown-item" href="{% url 'user_settings' %}">ユーザ設定</a>#}
    </div>
  </li>
{% endif %}