notice/urls.py
from django.urls import path

from . import views

app_name = "notice"
urlpatterns = [
    path("", views.index, name="index"),
]

shifttimes/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from custom_auth.views import activate_user
from shifttimes import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("", views.index, name="index"),
    path("forget/", include("custom_auth.forget_urls")),
    path("notice/", include("notice.urls")),
    path("activate/<uuid:activate_token>/", activate_user, name="activate_user"),
    path("profile/", include("custom_auth.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

custom_auth/models.py
import uuid

import pyotp
from django.apps import apps
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.db import models
from django.template.loader import render_to_string
from django.utils import timezone
from simple_history.models import HistoricalRecords

from custom_auth.utils import random_string
from shifttimes.models import MediumTextField


class GroupManager(models.Manager):
    def active_filter(self):
        return self.filter(is_active=True)

    def create_group(
        self, question, name, name_jp, postcode, address, address_jp, phone, country, contract_type,
        **extra_fields
    ):
        extra_fields.setdefault("is_pass", False)
        return self.create(
            agree=True,
            question=question,
            name=name,
            name_jp=name_jp,
            postcode=postcode,
            address=address,
            address_jp=address_jp,
            phone=phone,
            country=country,
            contract_type=contract_type,
            **extra_fields,
        )

    def update_group(self, group_id, postcode, address, address_en, phone, country):
        group = Group.objects.get(id=group_id)
        group.postcode = postcode
        group.address = address
        group.address_en = address_en
        group.phone = phone
        group.country = country
        group.save()


GROUP_STATUS_CHOICES = (
    (1, "有効"),
    (10, "ユーザより廃止"),
    (11, "運営委員より廃止"),
    (12, "審査落ち"),
)

# Membership
# 1-49 一般支払い
# 70-89 特別枠(無料)
# 90-99 特別枠(運営)
MEMBERSHIP_TYPE_CHOICES = (
    (1, "一般会員"),
    (40, "運営委員(優勝)"),
    (70, "学生委員"),
    (90, "運営委員(無償)"),
    (99, "その他"),
)

CONTRACT_TYPE_CHOICES = (
    ("E-Mail", "E-Mail"),
    ("AirMail", "AirMail)"),
)


class Group(models.Model):  # noqa: F811
    created_at = models.DateTimeField("作成日", default=timezone.now)
    updated_at = models.DateTimeField("更新日", default=timezone.now)
    name = models.CharField("name", max_length=150, unique=True)
    name_jp = models.CharField("name(japanese)", max_length=150, unique=True)
    comment = models.CharField("comment", max_length=250, default="", blank=True)
    status = models.IntegerField("ステータス", default=1, choices=GROUP_STATUS_CHOICES)
    allow_service_add = models.BooleanField("サービス追加許可", default=False)
    allow_jpnic_add = models.BooleanField("JPNIC情報追加許可", default=False)
    membership_type = models.IntegerField("会員種別", default=1, choices=MEMBERSHIP_TYPE_CHOICES)
    membership_expired_at = models.DateTimeField("有効期限", blank=True, null=True)

    # question
    agree = models.BooleanField("規約確認済み", default=False)
    is_pass = models.BooleanField("審査OK", default=False)

    # stripe
    stripe_customer_id = models.CharField("Stripe(CusID)", max_length=200, blank=True, null=True)

    # group personal info
    postcode = models.CharField("郵便番号", max_length=20, default="")
    address = models.CharField("住所", max_length=250, default="")
    address_jp = models.CharField("住所(Japanese)", max_length=250, default="")
    phone = models.CharField("phone", max_length=30, default="")
    country = models.CharField("居住国", max_length=100, default="Japan")
    contract_type = models.CharField("契約種別", max_length=100, default="E-Mail",
                                     choices=CONTRACT_TYPE_CHOICES)
    users = models.ManyToManyField(
        "User",
        blank=True,
        through="UserGroup",
        through_fields=("group", "user"),
        related_name="group_users_set",
    )
    history = HistoricalRecords()

    objects = GroupManager()

    class Meta:
        verbose_name = "グループ"
        verbose_name_plural = "グループ"

    def __str__(self):
        return "%s: %s" % (self.id, self.name)


class UserManager(BaseUserManager):
    def _create_user(self, username, username_jp, email, password, **extra_fields):
        if not username:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        username = GlobalUserModel.normalize_username(username)
        user = self.model(username=username, username_jp=username_jp, email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, username, username_jp, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_active", False)
        user = self._create_user(username, username_jp, email, password, **extra_fields)
        user_activate_token = UserActivateToken.objects.create(user=user)
        subject = "Please Activate Your Account"
        message = (
            f"URLにアクセスしてアカウントを有効化してください。\n "
            f"{settings.DOMAIN_URL}/activate/{user_activate_token.token}/"
        )
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [
            user.email,
        ]
        send_mail(subject, message, from_email, recipient_list)

        return user

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")

        return self._create_user(username, username, email, password, **extra_fields)

    def change_email(self, user=None, email=""):
        if not user:
            raise ValueError("user_id is not found......")
        if not email:
            raise ValueError("email is not found......")
        user.email = email
        user.is_active = False
        user_activate_token = UserActivateToken.objects.create(user=user)
        subject = "Please Activate Your Changed Email"
        message = (
            f"メールアドレスが変更されたので、URLにアクセスしてアカウントを有効化してください。\n"
            f" {settings.DOMAIN_URL}/activate/{user_activate_token.token}/"
        )
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [
            email,
        ]
        send_mail(subject, message, from_email, recipient_list)

        user.save()

    def update_user(self, user=None, name="", name_jp="", display_name=""):
        if not user:
            raise ValueError("user_id is not found......")
        if not name:
            raise ValueError("name is not found......")
        if not name_jp:
            raise ValueError("name_jp is not found......")
        if not display_name:
            raise ValueError("display_name is not found......")
        user.name = name
        user.name_jp = name_jp
        user.display_name = display_name
        user.save()


class User(AbstractBaseUser):
    username_validator = UnicodeUsernameValidator()

    created_at = models.DateTimeField("作成日", default=timezone.now)
    updated_at = models.DateTimeField("更新日", default=timezone.now)
    display_name = models.CharField("display_name", max_length=150, default="", blank=True)
    username = models.CharField("username", max_length=150, validators=[username_validator],
                                unique=True)
    username_jp = models.CharField("username(japanese)", max_length=150,
                                   validators=[username_validator], unique=True)
    email = models.EmailField("email", unique=True)
    is_staff = models.BooleanField("管理者ステータス", default=False)
    is_active = models.BooleanField("有効", default=False)
    allow_group_add = models.BooleanField("グループ追加許可", default=True)

    # stripe
    stripe_donate_customer_id = models.CharField("Stripe Donate(CusID)", max_length=200, blank=True,
                                                 null=True)

    groups = models.ManyToManyField(
        "Group",
        blank=True,
        through="UserGroup",
        through_fields=("user", "group"),
        related_name="user_set",
    )
    history = HistoricalRecords()

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    class Meta:
        verbose_name = "ユーザ"
        verbose_name_plural = "ユーザ"

    def __str__(self):
        return "%s: %s" % (self.id, self.username)

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_display_name(self):
        if self.display_name == "":
            return self.username
        return self.display_name

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

    def has_perm(self, perm, obj=None):
        if self.is_active and self.is_staff:
            return True

        return False

    def has_module_perms(self, app_label):
        if self.is_active and self.is_staff:
            return True

        return False


def user_activate_expire_date():
    return timezone.now() + timezone.timedelta(hours=settings.USER_LOGIN_VERIFY_EMAIL_EXPIRED_HOURS)


def email_verify_expire_date():
    return timezone.now() + timezone.timedelta(
        hours=settings.USER_LOGIN_VERIFY_EMAIL_EXPIRED_MINUTES)


class UserActivateTokensManager(models.Manager):
    def activate_user_by_token(self, activate_token):
        if not self.filter(token=activate_token, expired_at__gt=timezone.now()).exists():
            raise ValueError("Token is not found......")
        user_activate_token = self.filter(token=activate_token,

shifttimes/models.py
from django.db import models


class MediumTextField(models.TextField):
    def db_type(self, connection):
        if connection.settings_dict["ENGINE"] == "django.db.backends.mysql":
            return "mediumtext"
        else:
            return super(MediumTextField, self).db_type(connection=connection)

shifttimes/views.py
from django.contrib.auth import logout as user_logout, authenticate, login as user_login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from shifttimes.form import LoginForm


@login_required
def index(request):
    context = {}
    return render(request, "index.html", context)


def login(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user:
                user_login(request, user)
                return redirect("/")

    else:
        form = LoginForm()
    context = {'form': form}
    return render(request, "login.html", context)


@login_required
def logout(request):
    user_logout(request)
    context = {}
    return render(request, "logout.html", context)

shifttimes/templates/group/add.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2 class="card-title">Group新規申請</h2>
          <br/>
          {% if error %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
            <br/>
          {% endif %}
          {% if request.user.allow_group_add %}
            <form method="post" class="h-adr">
              {% csrf_token %}
              <a href="{% url 'custom_auth_group:index' %}"
                 class="nav-link text-white"
                 aria-current="page">
              </a>
              <h4>1. 申請内容</h4>
              <h5>{{ form.agree.label }}</h5>
              <a class="btn btn-primary btn-sm" onclick
                 href="{% get_fee_url %}"
                 target="_self">会費について</a>
              <a class="btn btn-primary btn-sm" onclick
                 href="{% get_usage_url %}"
                 target="_self">実験ネットワーク利用規約</a>
              <a class="btn btn-primary btn-sm" onclick
                 ref="{% get_privacy_policy_url %}"
                 target="_self">プライバシーポリシー</a>
              <br/>
              <br/>
              {{ form.agree }}
              {% if form.agree.error_messages %}
                <p class="link-danger">{{ form.agree.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.question1.label }}</h5>
              <p>
                当団体の運営委員より紹介を受けた方は紹介者の名前を記入してください</p>
              {{ form.question1 }}
              {% if form.question1.error_messages %}
                <p class="link-danger">{{ form.question1.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.question2.label }}</h5>
              <p>例)
                研究目的、勉強、自宅サーバ用途（商用利用は不可）[10文字以上]</p>
              {{ form.question2 }}
              {% if form.question2.error_messages %}
                <p class="link-danger">{{ form.question2.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.question3.label }}</h5>
              <p>
                PIアドレスやAS番号をお持ちの方は、それらをご利用いただくことも可能です</p>
              {{ form.question3 }}
              {% if form.question3.error_messages %}
                <p class="link-danger">{{ form.question3.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.question4.label }}</h5>
              <p>GitHub、成果物などがありましたら教えてください<br/>(発信しているコンテンツなどがなければ、「なし」とお答えください)
              </p>
              {{ form.question4 }}
              {% if form.question4.error_messages %}
                <p class="link-danger">{{ form.question4.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <br/>
              <h4>2. 組織情報</h4>
              <h5>{{ form.name.label }}</h5>
              {{ form.name }}
              {% if form.name.error_messages %}
                <p class="link-danger">{{ form.name.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.name_jp.label }}</h5>
              {{ form.name_jp }}
              {% if form.name_jp.error_messages %}
                <p class="link-danger">{{ form.name_jp.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.postcode.label }}</h5>
              {{ form.postcode }}
              {% if form.postcode.error_messages %}
                <p class="link-danger">{{ form.postcode.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.address.label }}</h5>
              {{ form.address }}
              {% if form.address.error_messages %}
                <p class="link-danger">{{ form.address.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.address_jp.label }}</h5>
              {{ form.address_jp }}
              {% if form.address_jp.error_messages %}
                <p class="link-danger">{{ form.address_jp.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.phone.label }}</h5>
              {{ form.phone }}
              {% if form.phone.error_messages %}
                <p class="link-danger">{{ form.phone.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h5>{{ form.country.label }}</h5>
              {{ form.country }}
              {% if form.country.error_messages %}
                <p class="link-danger">{{ form.country.error_messages | striptags }}</p>
              {% endif %}
              <br/>
              <h4>{{ form.contract.label }}</h4>
              <p> 当団体は電気通信事業者として届出を行っておりますため、利用開始時に電気通信事業法<br/>
                第26条2（書面の交付義務）に基づき、<br/>
                ご利用内容をお知らせいたしますので、ご希望の交付方法をお知らせください。
              </p>
              {{ form.contract }}
              {% if form.contract.error_messages %}
                <p class="link-danger">{{ form.contract.error_messages | striptags }}</p>
              {% endif %}


              <br/>
              <button type="submit" class="btn btn-primary">登録</button>
            </form>
          {% else %}
            <p>
              <b>新規にグループを登録したい又は既存の登録グループを紐づけたい方は、チケットページよりお問い合わせください</b>
            </p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

shifttimes/templates/group/edit.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2 class="card-title">Group情報閲覧・修正</h2>
          <br/>
          {% if error %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
            <br/>
          {% endif %}
          {% if group %}
            <div class="card">
              <div class="card-header">
                ID: {{ group.id }} 作成日: {{ group.created_at }}
              </div>
            </div>
            <br/>
            <br/>
            <form method="post" class="h-adr">
              {% csrf_token %}
              {{ form }}
              <br/>
              {% if group.status == 1 and is_administrator %}
                <button type="submit" class="btn btn-primary">変更
                </button>{% endif %}
            </form>
          {% else %}
            <p><b>本グループIDは閲覧できません</b></p>
          {% endif %}
          <br/>
          <br/>
          <a class="btn btn-primary"
             href="{% url 'custom_auth_group:index' %}" role="button"
             aria-expanded="false">グループ一覧に戻る</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

shifttimes/templates/group/edit_permission.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2 class="card-title">Group権限設定</h2>
          <br/>
          {% if error %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
            <br/>
          {% endif %}
          {% if group %}
            <div class="card">
              <div class="card-header">
                ID: {{ group.id }} 作成日: {{ group.created_at }}
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ group.name }}</h5>
                <br/>
              </div>
              <div class="card-footer">
                {% if group.status == 1 %}
                  <span class="badge bg-primary">有効</span>
                {% else %}
                  <span class="badge bg-danger">無効</span>{% endif %}
                {% if is_administrator %}
                  <span class="badge bg-success">管理者権限</span>{% endif %}
                <span
                    class="badge bg-secondary">Service: {{ group.service_set.count }}</span>
              </div>
            </div>
            <br/>
            <br/>
            {% if permissions %}
              <table class="table table-striped">
                <thead>
                <tr>
                  <th scope="col">ID</th>
                  <th scope="col">作成日</th>
                  <th scope="col">User</th>
                  <th scope="col">Group</th>
                  <th scope="col">Option</th>
                  <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for permission in permissions %}
                  <tr>
                    <th scope="row">{{ permission.id }}</th>
                    <td>{{ permission.created_at }}</td>
                    <td>{{ permission.user.id }}: {{ permission.user.username }}</td>
                    <td>{{ permission.group.id }}: {{ permission.group.name }}</td>
                    <td>
                      {% if permission.is_admin %}
                        <span class="badge bg-success">管理者権限</span>
                      {% else %}
                        <span class="badge bg-primary">ユーザ権限</span>
                      {% endif %}
                      {% if permission.enable_ldap %}
                        <span class="badge bg-success">LDAP有効</span>
                      {% elif permission.ldap_register %}
                        <span class="badge bg-danger">LDAP無効</span>
                      {% endif %}
                    </td>
                    <td>
                      {% if is_administrator %}
                        <form method="post">
                          {% csrf_token %}
                          <input type="text"
                                 value={{ permission.id }} name="id"
                                 hidden>
                          {% if permission.is_admin and permission.user.id != request.user.id %}
                            <button type="submit"
                                    class="btn btn-primary btn-sm"
                                    name="no_admin">ユーザ権限に変更
                            </button>
                          {% elif permission.is_admin %}
                            ユーザ権限に変更出来ません
                          {% else %}
                            <button type="submit"
                                    class="btn btn-primary btn-sm"
                                    name="admin">管理者権限に変更
                            </button>
                          {% endif %}
                        </form>
                      {% else %}
                        権限がありません
                      {% endif %}
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            {% endif %}
            {% if not is_administrator %}
              <p>管理者権限がないため、権限設定を変更出来ません。</p>
            {% endif %}
          {% else %}
            <p><b>本グループIDは閲覧できません</b></p>
          {% endif %}
          <br/>
          <br/>
          <a class="btn btn-primary"
             href="{% url 'custom_auth_group:index' %}" role="button"
             aria-expanded="false">グループ一覧に戻る</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

shifttimes/templates/group/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2 class="card-title"><b>グループ一覧</b></h2>
          <br/>
          {% if request.user.allow_group_add %}
            <p><b>下記のより、新規申請してください。</b></p>
            <a class="btn btn-primary"
               href="{% url 'custom_auth_group:add' %}" role="button"
               aria-expanded="false">新規申請</a>
          {% else %}
            <p>
              <b>グループの追加申請は原則1つまでです</b>
            </p>
          {% endif %}
          <br/>
          <br/>
          {% if groups %}
            {% for group in groups %}
              <div class="card">
                <div class="card-header">
                  ID: {{ group.data.id }}
                  作成日: {{ group.data.created_at }}
                </div>
                <div class="card-body">
                  <h5 class="card-title">{{ group.data.name }}</h5>
                  <p class="card-text">
                    会員種別: <b>{{ group.data.get_membership_type_display }}</b><br/>
                  {% if group.data.membership_type < 50 %}
                    有効期限: <b>{{ group.data.membership_expired_at }}まで</b>
                  {% else %}
                    課金情報: <b>課金ステータス無効</b>
                  {% endif %}
                  </p>
                  <div class="container">
                    <div>
                      <a class="btn btn-primary btn-sm"
                         href="{% url 'custom_auth_group:edit' group.data.id %}">情報閲覧・修正</a>
                      <a class="btn btn-primary btn-sm"
                         href="{% url 'custom_auth_group:permission' group.data.id %}">権限設定</a>
                      <a class="btn btn-primary btn-sm"
                         href="{% url 'custom_auth_group:payment' group.data.id %}">会費支払い情報</a>
                      <a class="btn btn-primary btn-sm"
                         href="{% url 'service:index' group.data.id %}">サービス情報</a>
                      <a class="btn btn-primary btn-sm"
                         href="{% url 'jpnic:jpnic_index' group.data.id %}">JPNIC情報</a>
                      <br/>
                      <br/>
                      {% if e.administrator %}
                        <form method="post">
                          {% csrf_token %}
                          <input type="text" value={{ group.data.id }} name="group_id" hidden>
                          {% if group.data.is_charge and group.data.stripe_customer_id and not group.data.stripe_subscription_id %}
                            <a class="btn btn-primary btn-sm"
                               href="{% url 'group_payment' group.data.id %}">会費のお支払いはこちらから</a>
                          {% endif %}
                          {% if not group.data.stripe_customer_id %}
                            <button type="submit" name="id"
                                    value="create_stripe_customer"
                                    class="btn btn-primary btn-sm">
                              会費のお支払いはこちらから
                            </button>
                          {% endif %}
                          {% if group.data.is_charge and group.data.stripe_customer_id %}
                            <button type="submit" name="id"
                                    value="getting_portal"
                                    class="btn btn-primary btn-sm">
                              プランの変更・キャンセル
                            </button>
                          {% endif %}
                        </form>
                      {% endif %}
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  {% if group.data.is_pass %}
                    <span class="badge bg-primary">審査済</span>
                  {% else %}
                    <span class="badge bg-danger">未審査</span>{% endif %}
                  {% if group.administrator %}
                    <span class="badge bg-success">管理者権限</span>{% endif %}
                  <span
                      class="badge bg-secondary">Service: {{ group.data.service_set.count }}</span>
                </div>
              </div>
              <br/>
            {% endfor %}
          {% else %}
            <p>グループがありません</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}