custom_auth/urls.py
from django.urls import path

from . import views

app_name = "custom_auth"
urlpatterns = [
    path("", views.index, name="index"),
    path("password", views.password_change, name="password_change"),
    path("email", views.change_email, name="email_change"),
    path("edit", views.edit_profile, name="edit_profile"),
    path("two_auth", views.list_two_auth, name="list_two_auth"),
    path("two_auth/add", views.add_two_auth, name="add_two_auth"),
]

notice/urls.py
from django.urls import path

from . import views

app_name = "notice"
urlpatterns = [
    path("", views.index, name="index"),
]

shifttimes/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from custom_auth.views import activate_user
from shifttimes import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("", views.index, name="index"),
    path("forget/", include("custom_auth.forget_urls")),
    path("notice/", include("notice.urls")),
    path("activate/<uuid:activate_token>/", activate_user, name="activate_user"),
    path("profile/", include("custom_auth.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

shifttimes/models.py
from django.db import models


class MediumTextField(models.TextField):
    def db_type(self, connection):
        if connection.settings_dict["ENGINE"] == "django.db.backends.mysql":
            return "mediumtext"
        else:
            return super(MediumTextField, self).db_type(connection=connection)

shifttimes/views.py
from django.contrib.auth import logout as user_logout, authenticate, login as user_login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from shifttimes.form import LoginForm


@login_required
def index(request):
    context = {}
    return render(request, "index.html", context)


def login(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user:
                user_login(request, user)
                return redirect("/")

    else:
        form = LoginForm()
    context = {'form': form}
    return render(request, "login.html", context)


@login_required
def logout(request):
    user_logout(request)
    context = {}
    return render(request, "logout.html", context)

shifttimes/templates/user/two_auth/add.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2 class="card-title">2段階認証デバイス登録</h2>
          <br/>
          {% if initial_check %}
            <img src="data:image/png;base64,{{ qr }}" width="250"/>
            <br/>
            <br/>
            <br/>
            {% if error %}
              <div class="alert alert-danger" role="alert">
                {{ error }}
              </div>
            {% endif %}
            <form method="post">
              {% csrf_token %}
              <input type="text" value='{{ secret }}' name="secret"
                     hidden>
              <label for="floatingInput">{{ form.title.label }}</label>
              {{ form.title }}
              <label for="id_password">{{ form.code.label }}</label>
              {{ form.code }}
              <br/>
              <br/>
              <button type="submit" name="id" value="submit"
                      class="btn btn-primary">登録
              </button>
            </form>
          {% else %}
            <div class="alert alert-danger" role="alert">
              登録数が上限を超えてます。
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

shifttimes/templates/user/two_auth/list.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2 class="card-title">2段階認証リスト</h2>
          <br/>
          <a class="btn btn-primary btn-sm "
             href="{% url 'custom_auth:add_two_auth' %}" role="button"
             aria-expanded="false">デバイス登録</a>
          <br/>
          <br/>
          {% if devices %}
            {% for device in devices %}
              <div class="card">
                <div class="card-header">
                  ID: {{ device.id }} 作成日: {{ device.created_at }}
                </div>
                <div class="card-body">
                  <h5 class="card-title">{{ device.title }}</h5>
                  <div class="container">
                    <div class="row">
                      <form method="post">
                        {% csrf_token %}
                        <input type="text"
                               value={{ device.id }} name="device_id"
                               hidden>
                        <button type="submit"
                                class="btn btn-warning btn-sm"
                                name="id"
                                value="delete">削除
                        </button>
                      </form>
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  {% if device.is_active %}
                    <span class="badge bg-primary">有効</span>
                  {% else %}
                    <span class="badge bg-danger">無効(再認証が必要)</span>{% endif %}
                </div>
              </div>
              <br/>
            {% endfor %}
          {% else %}
            <p>2段階認証が登録されていません</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}