custom_auth/urls.py
from django.urls import path

from . import views

app_name = "custom_auth"
urlpatterns = [
    path("", views.index, name="index"),
    path("password", views.password_change, name="password_change"),
    path("email", views.change_email, name="email_change"),
    path("edit", views.edit_profile, name="edit_profile"),
    path("two_auth", views.list_two_auth, name="list_two_auth"),
    path("two_auth/add", views.add_two_auth, name="add_two_auth"),
]

notice/urls.py
from django.urls import path

from . import views

app_name = "notice"
urlpatterns = [
    path("", views.index, name="index"),
]

shifttimes/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from custom_auth.views import activate_user
from shifttimes import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("", views.index, name="index"),
    path("forget/", include("custom_auth.forget_urls")),
    path("notice/", include("notice.urls")),
    path("activate/<uuid:activate_token>/", activate_user, name="activate_user"),
    path("profile/", include("custom_auth.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

shifttimes/models.py
from django.db import models


class MediumTextField(models.TextField):
    def db_type(self, connection):
        if connection.settings_dict["ENGINE"] == "django.db.backends.mysql":
            return "mediumtext"
        else:
            return super(MediumTextField, self).db_type(connection=connection)

shifttimes/views.py
from django.contrib.auth import logout as user_logout, authenticate, login as user_login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from shifttimes.form import LoginForm


@login_required
def index(request):
    context = {}
    return render(request, "index.html", context)


def login(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user:
                user_login(request, user)
                return redirect("/")

    else:
        form = LoginForm()
    context = {'form': form}
    return render(request, "login.html", context)


@login_required
def logout(request):
    user_logout(request)
    context = {}
    return render(request, "logout.html", context)

shifttimes/templates/user/change_email.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2>パスワード変更</h2>
          <div class="row justify-content-md-center">
            <div class="col-8">
              <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                  <div class="form-group">
                    <label class="col-6"
                           for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                  </div>
                {% endfor %}
                {% csrf_token %}
                <br/>
                <button type="submit" class="btn btn-primary btn-block">
                  送信
                </button>
              </form>
              <br/>
              <br/>
              <a href="{% url 'custom_auth:index' %}"
                 class="btn btn-primary">プロフィールに戻る</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

shifttimes/templates/user/change_password.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2>パスワード変更</h2>
          <div class="row justify-content-md-center">
            <div class="col-8">
              <div class="card text-bg-warning mb-3">
                <div class="card-body">
                  <h5 class="card-title">注意点</h5>
                  <div class="card-text">
                    <ul>
                      <li>
                        ご登録情報に似たパスワードにはできません。
                      </li>
                      <li>8文字以上32文字以内で設定してください。
                      </li>
                      <li>よく使われるパスワードにはできません。
                      </li>
                      <li>数字だけのパスワードにはできません。</li>
                    </ul>
                  </div>
                </div>
              </div>
              {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ form.errors }}
                </div>
              {% endif %}
              <form method="post">
                {% csrf_token %}
                <p>元のパスワード:{{ form.old_password }}</p>
                <p>新しいパスワード:{{ form.new_password1 }}</p>
                <p>新しいパスワード（確認用）:{{ form.new_password2 }}</p>
                <input type="submit" class="btn btn-primary"/>
              </form>
              <br/>
              <br/>
              <a href="{% url 'custom_auth:index' %}"
                 class="btn btn-primary">プロフィールに戻る</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

shifttimes/templates/user/edit_profile.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2>プロフィールの閲覧・変更</h2>
          <div class="row justify-content-md-center">
            <div class="col-8">
              <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                  <div class="form-group">
                    <label class="col-6"
                           for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                  </div>
                {% endfor %}
                {% csrf_token %}
                <br/>
                <button type="submit" class="btn btn-primary btn-block">
                  送信
                </button>
              </form>
              <br/>
              <br/>
              <a href="{% url 'custom_auth:index' %}"
                 class="btn btn-primary">プロフィールに戻る</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

shifttimes/templates/user/profile.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="container py-4 mb-auto">
        <div class="h-900 p-2 rounded-3">
          <h2 class="card-title">Profile</h2>
          <br/>
          <div class="card mb-2">
            <div class="card-header">
              ID: {{ user.id }}
            </div>
            <div class="card-body">
              <h5 class="card-title">{{ user.username }}
                ({{ user.username_jp }})</h5>
              <div class="container">
                <div class="row">

                </div>
              </div>
            </div>
            <div class="card-footer">
              <span
                  class="badge bg-secondary">作成日: {{ request.user.created_at }}</span>
              <span
                  class="badge bg-secondary">最終Login日: {{ request.user.last_login }}</span>
              {% if user.is_active %}
                <span class="badge bg-success">有効</span>
              {% else %}
                <span class="badge bg-danger">無効</span>{% endif %}
              {% if user.is_staff %}
                <span class="badge bg-primary">dsbd管理者</span>{% endif %}
            </div>
          </div>
          <hr/>
          <a class="btn btn-primary btn-sm"
             href="{% url 'custom_auth:password_change' %}" role="button"
             aria-expanded="false">パスワード変更</a>
          <a class="btn btn-primary btn-sm"
             href="{% url 'custom_auth:email_change' %}" role="button"
             aria-expanded="false">メールアドレス変更</a>
          <a class="btn btn-primary btn-sm"
             href="{% url 'custom_auth:edit_profile' %}" role="button"
             aria-expanded="false">プロフィール閲覧・変更</a>
          <hr/>
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">2段階認証のデバイス追加</h5>
              <div class="container">
                2段階認証用のデバイスを追加したい場合はこちらを選択してください。
              </div>
              <br/>
              <a type="submit" class="btn btn-primary"
                 href="{% url 'custom_auth:list_two_auth' %}">2段階認証のデバイス追加</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}